### PR TITLE
Fixed single-thread reactors not running in single-thread.

### LINKED ISSUE #8: single-threaded reactors not run single-threaded.
**Actual Result**
Reactors defined as `single-thread="true"` still receive the threading flags from the command line.

**Expected Result**
Single-threaded reactors should be invoked in a single-threaded manner.

### PR DESCRIPTION
**Pull request by ivanjensen-ep**
Fixes #8

### CODE REVIEW

File: src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java [hunk 1]
```diff
@@ -145,6 +147,28 @@ private static CommandLine determineMavenCommand(final Reactor reactor, final Li
...
+		for (Iterator<String> iter = mavenArguments.iterator(); iter.hasNext();) {
+			String arg = iter.next();
+			if (arg.matches("(-T|--threads)")) {
+				iter.remove();          // Remove the flag
+				if (iter.hasNext()) {   // Remove the argument
+					iter.next();
+					iter.remove();
+				}
+			}
+		}
```
Comment (gdenning) [inline src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java:169]: Isn't this iterator doing exactly the same thing as the "removeIf" on line 158?

Comment (ivanjensen-ep) [reply src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java:169]: No, 158 gets rid of the flags with have spaces: `-T4` or `--threads=4`
This iterator deals with flags that are provided with a space (and therefore two list elements): `-T 4` or `--threads 4`

Comment (gdenning) [reply src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java:169]: I guess not exactly, but couldn't the "removeIf" be updated to "(-T.+.*|--threads=.*|-T|--threads)"?

File: src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java [hunk 2]
```diff
@@ -145,6 +147,28 @@ private static CommandLine determineMavenCommand(final Reactor reactor, final Li
...
 
+
+	/**
+	 * The number of threads can be specified in several ways for Maven, each possibility needs to be removed.
+	 * This method
+	 * @param mavenArguments the arguments to pass to maven.
+	 */
+	static void removeThreadingFlags(final List<String> mavenArguments) {
+
+		mavenArguments.removeIf(s -> s != null && s.matches("(-T.+.*|--threads=.*)"));
```
Comment (gdenning) [inline src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java:158]: Would this change allow us to remove the iterator?

```suggestion
		mavenArguments.removeIf(s -> s != null && s.matches("(-T.+.*|--threads=.*|-T|--threads)"));
```

File: src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java (hunk 1 above)
Comment (gdenning) [reply src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java:169]: See my new comment above.

File: src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java (hunk 2 above)
Comment (ivanjensen-ep) [reply src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java:158]: No, because we need to remove two separate list items, not just one.

Comment (gdenning) [reply src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java:158]: Ohhhhh...ok, I get it.

File: src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java [hunk 3]
```diff
@@ -125,7 +126,8 @@ private static CommandLine determineMavenCommand(final Reactor reactor, final Li
 		}
 
 		if (reactor.isSingleThread()) {
-			mavenArguments.removeIf(s -> s != null && s.matches("-T.*"));
+			removeThreadingFlags(mavenArguments);
+			mavenArguments.add("-T1");
```
Comment (gdenning) [inline src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java:130]: Is this necessary?

File: src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java [hunk 4]
```diff
@@ -145,6 +147,28 @@ private static CommandLine determineMavenCommand(final Reactor reactor, final Li
 		return cmdLine;
 	}
 
+
+	/**
+	 * The number of threads can be specified in several ways for Maven, each possibility needs to be removed.
+	 * This method
```
Comment (gdenning) [inline src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java:153]: Incomplete sentence?

File: src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java (hunk 3 above)
Comment (ivanjensen-ep) [reply src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java:130]: I'm not 💯 , but this felt it made things very explicit: it forces a single-thread, rather than relying on Maven to do just do that.

**Review by gdenning — APPROVED** [review]

File: src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java (hunk 4 above)
Comment (ivanjensen-ep) [reply src/main/java/com/elasticpath/tools/mavenminimal/reactor/MavenDriver.java]: Fixed, thanks!
